### PR TITLE
Fix the collate in build command.

### PR DESCRIPTION
**Pull request by YuheiTakagawa**
Check Characterset only, CollationName is not checked.

Example: 
newCol.CharacterSetName = utf8bm4
newCol.CollationName = utf8bm4-bin

oldCol.CharacterSetName = utf8bm4
oldCol.CollationName = utf8bm4-general-ci

In this case, `!newCol.CharacterSetName.Valid || oldCol.CompareCharacterSet(newCol)` is (false || true).
CollationName is not modified by build cmd.

I add function to compare CollationName.

### CODE REVIEW

**Comment by hatajoe** [comment]
@YuheiTakagawa So sorry for the late too... and thank you for reporting the bug. It looks good to me.
Can I request you to write a test for this?

**Comment by YuheiTakagawa** [comment]
Hi, @hatajoe 
I changed test file for changing collation.

Also, I refactored willAlter, willAlterTableCharacterSet and willAlterColumnCharacterSet.
The reason is these functions call alter separately though it was the same table.

**Comment by hatajoe** [comment]
@YuheiTakagawa Thank you for responding to my request. However, the test seems to fail. 
Could you rebase (or merge) the master, and push it again?

**Comment by YuheiTakagawa** [comment]
Hi, @hatajoe 
I pushed with rebase the master.
I confirmed all test succeeded with below.

```
go clean --testcache
go test ./...
```

Please check it again.

**Comment by hatajoe** [comment]
@YuheiTakagawa Thank you for responding. I checked to finish all of the tests correctly. LGTM!

**Pull request merged**
