### PR TITLE
<feature proposal> ignore foreign key when import command

### PR DESCRIPTION
**Pull request by tacogips**
Thanks to maintain good migration tool. I about to use this tool in production.

when I execute import command,  I got  ` failed for reason Error 1452: Cannot add or update a child row: a foreign key constraint fails ... ` error.
To avoid this, I made reference implement to execute `SET foreign_key_checks = 0` before insertion.
I hope you will consider this or is there any other walk around ?

---

I set MaxOpenConns to 1 because `SET foreign_key_checks = 0` not work if another connection(that has default setting) in connection pool used for insertion.
we need to find another way if it leads to  performance issue.

### CODE REVIEW

**Comment by hatajoe** [comment]
@tacogips Thank you for your PR! Sorry for the delay in responding.

I usually don't use foreign keys, thus I don't familiar with FK, but I understood that it is the problem with this tool.

I don't think so that is good to change embedded max-connection settings. 
Concurrent importing is important for performance in daily migration.

How about would be good to set max-connection by cmd options?
For example, separate two or more directories that contain CSV files having FK relationships. 
And doing like below:

```
% carpenter import --max-idle-conns=1 --max-open-conns=1 -d ./csv/contains_fk_relationships/
% carpenter import -d ./csv/no_fk_relationships/
```

import command will work fine.

`--max-idle-conns=1` and `--max-open-conns=1` are seemed little bit implicit for using... 
`--single-conn` may have a more good expression instead of that...How do you think about?

Thank you.

**Comment by tacogips** [comment]
thanks for your response. 

> --max-idle-conns=1 and --max-open-conns=1 are seemed little bit implicit for using...
> --single-conn may have a more good expression instead of that...How do you think about?

single-conn is simple but , it may used in limited situation.  I prefer setting max-idle-conns and max-open-conns explicitly , though it's a little bit redundant but could be used in general situation.

**Comment by hatajoe** [comment]
@tacogips Good, you are right. I'll implement it within a few days.

**Comment by hatajoe** [comment]
@tacogips I implemented two flags as cmd arguments and created the PR tacogips/carpenter#1. 
Could you please review and merge?

**Comment by tacogips** [comment]
sorry for late reply.  I merged the PR

**Comment by hatajoe** [comment]
@tacogips Thanks!

**Comment by hatajoe** [comment]
Release: https://github.com/dev-cloverlab/carpenter/releases/tag/v0.5.4

**Pull request merged**
